name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Change to your preferred Python version

    - name: Install AWS CLI and SAM CLI
      run: |
        pip install awscli
        pip install aws-sam-cli

    - name: Setting AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.DEFAULT_AWS_REGION }}
        aws configure set output json

    - name: Creating S3 management bucket for AWS SAM
      run : |
        aws s3api create-bucket --bucket SAM-management --region ${{ secrets.DEFAULT_AWS_REGION }}

    - name: Deploy SAM Application
      run: |
        sam build
        sam deploy --stack-name youtube --s3-bucket management --capabilities CAPABILITY_IAM --parameter-overrides ParameterKey=AccessKeyId,ParameterValue=${{ secrets.AWS_ACCESS_KEY_ID }} ParameterKey=SecretAccessKey,ParameterValue=${{ secrets.AWS_SECRET_ACCESS_KEY }} ParameterKey=GoogleApiKey,ParameterValue=${{ secrets.GOOGLE_API_KEY }} ParameterKey=DefaultRegion,ParameterValue=${{ secrets.DEFAULT_AWS_REGION }} ParameterKey=AdminUsername,ParameterValue=${{ secrets.ADMINUSERNAME }} ParameterKey=AdminUserPassword,ParameterValue=${{ secrets.ADMINUSERPASSWORD }} 
